### ISSUE TITLE
Divide the cards of the Vanguard set into Vanguard and Vanguard(Online)

### ISSUE THREAD

**Issue by tomato889** [Sembiance/mtgjson#82] opened 2015-10-05 17:58 UTC
As of now, the Vanguard set consists of the paper Vanguard cards (http://www.magiclibrarities.net/291-rarities-vanguard-cards-english-cards-index.html) as well as the online only avatars and isn't marked as online only.

The set should be split into two sets, since except for the name and the card types the two sets are distinct.

**Comment by Sembiance** [comment] 2015-10-05 18:16
Duplicate of #49

**Closed by Sembiance** 2015-10-05 18:16 UTC
